{
  "openapi": "3.0.0",
  "info": {
    "title": "WriteUp API",
    "version": "1.0.0",
    "description": "API documentation"
  },
  "host": "localhost:5001",
  "basePath": "/api-v1",
  "paths": {
    "/api-v1/articles": {
      "get": {
        "summary": "Get list of all articles",
        "description": "Returns a list of articles with the corresponding user likes.",
        "tags": ["Article"],
        "parameters": [
          {
            "in": "query",
            "name": "sort",
            "schema": { "type": "string", "example": "like" }
          },
          {
            "in": "query",
            "name": "page",
            "schema": { "type": "Number", "example": 2 }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "title": "Introduction to JavaScript",
                  "description": "Learn the basics of JavaScript programming language",
                  "content": "JavaScript is a versatile scripting language used for...",
                  "total_likes": 25,
                  "background_url": "/image/java.jpg",
                  "created_at": 2024,
                  "isLiked": 0
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a new article",
        "description": "Creates a new article.",
        "tags": ["Article"],
        "requestBody": {
          "description": "article data for create",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": { "type": "string", "example": "nodejs" },
                  "description": { "type": "string", "example": "this is test" },
                  "content": {
                    "type": "string",
                    "example": "this is test content here"
                  },
                  "background_url": {
                    "type": "string",
                    "example": "it is actual file name and its extension"
                  },
                  "tag": { "type": "string", "example": "javascript" }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "article created successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 201,
                  "articleId": 19,
                  "message": "article created successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api-v1/articles/{slug}": {
      "get": {
        "summary": "Get one specefic of  articles",
        "description": "Returns a article with the corresponding slug.",
        "tags": ["Article"],
        "parameters": [
          {
            "in": "path",
            "name": "slug",
            "schema": { "type": "string", "example": "javascript-test" }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "title": "Introduction to JavaScript",
                  "uniqueSlug": "Introduction-to-JavaScript",
                  "description": "Learn the basics of JavaScript programming language",
                  "content": "JavaScript is a versatile scripting language used for...",
                  "total_likes": 25,
                  "background_url": "/image/java.jpg",
                  "created_at": 2024,
                  "isLiked": 0
                }
              }
            }
          }
        }
      }
    },
    "/api-v1/articles/{id}": {
      "patch": {
        "summary": "update specefic article",
        "description": "update specefic article by its id.",
        "tags": ["Article"],
        "requestBody": {
          "description": "article data for update",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": { "type": "string", "example": "nodejs" },
                  "description": { "type": "string", "example": "this is test" },
                  "content": {
                    "type": "string",
                    "example": "this is test content here"
                  },
                  "background_url": {
                    "type": "string",
                    "example": "it is actual file name and its extension"
                  },
                  "tag": { "type": "string", "example": "javascript" }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "article update successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": 201,
                  "articleId": 19,
                  "message": "article created successfully"
                }
              }
            }
          },
          "404": { "description": "article not found." }
        }
      },
      "delete": {
        "summary": "delete specific article",
        "description": "delte an article by its id.",
        "tags": ["Article"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": { "type": "string" },
            "description": "The ID of the article to delete."
          }
        ],
        "responses": {
          "200": {
            "description": "article deleted successfully",
            "content": {
              "application/json": { "example": { "message": "article deleted successfully" } }
            }
          },
          "404": {
            "description": "article not found",
            "content": {
              "application/json": { "example": { "message": "article not found" } }
            }
          }
        }
      }
    },
    "/api-v1/articles/like/{id}": {
      "post": {
        "summary": "Like or unlike an article",
        "description": "Likes and unlike an article by its ID.",
        "tags": ["Article"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": { "type": "string" },
            "description": "The ID of the article to like or unlike."
          }
        ],
        "responses": {
          "200": {
            "description": "article liked | unliked",
            "content": {
              "application/json": { "example": { "message": "article liked | unliked" } }
            }
          }
        }
      }
    },
    "/api-v1/articles/search": {
      "get": {
        "summary": "searcj for articles",
        "description": "get a list of matched articles",
        "tags": ["Article"],
        "parameters": [
          {
            "in": "query",
            "name": "s",
            "schema": { "type": "string", "example": "javascript" }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": { "type": "string", "example": "like" }
          },
          {
            "in": "query",
            "name": "page",
            "schema": { "type": "number", "example": 2 }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "title": "Introduction to JavaScript",
                  "description": "Learn the basics of JavaScript programming language",
                  "content": "JavaScript is a versatile scripting language used for...",
                  "total_likes": 25,
                  "background_url": "/image/java.jpg",
                  "created_at": 2024,
                  "isLiked": 0
                }
              }
            }
          }
        }
      }
    },
    "/api-v1/articles/tags": {
      "get": {
        "summary": "get all tags",
        "description": "get a list of articles tags",
        "tags": ["Article"],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": { "Tags": "cloud-computing,css,databases,devops,docker" }
              }
            }
          }
        }
      }
    },
    "/api-v1/auth/signin": {
      "post": {
        "summary": "User Sign-In",
        "description": "Authenticates a user and generates a JWT token\n",
        "tags": ["Authentication"],
        "requestBody": {
          "description": "User data for sign-in",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string", "example": "mahyar@m.com" },
                  "password": { "type": "string", "example": "123456AA" }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sign-in successful",
            "content": {
              "application/json": {
                "example": {
                  "status": 200,
                  "message": "Sign-in successful",
                  "id": 19,
                  "username": "mahyarGDZ",
                  "email": "mahyar@m.com..."
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": { "status": 401, "message": "Invalid email or password" }
              }
            }
          }
        }
      }
    },
    "/api-v1/auth/signup": {
      "post": {
        "summary": "User Sign-Up",
        "description": "Creates a new user account with the provided data.",
        "tags": ["Authentication"]
      }
    },
    "/api-v1/auth/check-login": {
      "get": {
        "summary": "Check User Login Status",
        "description": "Checks if a user is currently logged in by verifying their authentication token.",
        "tags": ["Authentication"],
        "responses": {
          "200": {
            "description": "loggedIn=1",
            "content": {
              "application/json": {
                "example": {
                  "status": 200,
                  "loggedin": 1,
                  "userInfo": { "id": 1, "username": "mahyar..." }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": { "example": { "status": 401, "loggedin": 0 } }
            }
          }
        }
      }
    },
    "/api-v1/auth/logout": {
      "get": {
        "summary": "User Logout",
        "description": "Logs out the currently authenticated user by clearing their cookies.",
        "tags": ["Authentication"],
        "responses": {
          "200": {
            "description": "user Logged out",
            "content": {
              "application/json": { "example": { "message": "User logged out" } }
            }
          }
        }
      }
    },
    "/api-v1/users": {
      "get": {
        "summary": "Get list of all users",
        "description": "Returns a list of users.",
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "username": "mahyargdz",
                  "email": "m@m.com",
                  "isAdmin": 1,
                  "isPremium": 1,
                  "email_validated": 1,
                  "created_at": 2024
                }
              }
            }
          }
        }
      }
    },
    "/api-v1/users/search": {
      "get": {
        "summary": "search for user",
        "description": "get a list of matched users",
        "tags": ["Users"],
        "parameters": [
          {
            "in": "query",
            "name": "s",
            "schema": { "type": "string", "example": "mahyar" }
          },
          {
            "in": "query",
            "name": "page",
            "schema": { "type": "number", "example": 2 }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "username": "hassan",
                  "email": "m@m.com",
                  "isAdmin": 1,
                  "isPremium": 1,
                  "email_validated": 1,
                  "created_at": 2024
                }
              }
            }
          }
        }
      }
    },
    "/api-v1/users/{email}": {
      "get": {
        "summary": "Get one specefic of users",
        "description": "Returns a detail of user.",
        "tags": ["Users"],
        "parameters": [
          {
            "in": "path",
            "name": "email",
            "schema": { "type": "string", "example": "mahyar@mahyar.com" }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "username": "mahyargdz",
                  "email": "m@m.com",
                  "isAdmin": 1,
                  "isPremium": 1,
                  "email_validated": 1,
                  "created_at": 2024
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete a specefic user",
        "description": "delete one user by its id.",
        "tags": ["Users"],
        "parameters": [
          {
            "in": "path",
            "name": "email",
            "schema": { "type": "string" },
            "description": "The email of the user to delete."
          }
        ],
        "responses": {
          "200": {
            "description": "user deleted successfully",
            "content": {
              "application/json": { "example": { "message": "user deleted successfully" } }
            }
          },
          "403": { "description": "can not delete current user" },
          "404": { "description": "user not found" }
        }
      }
    },
    "/api-v1/users/{id}": {
      "patch": {
        "summary": "update a specefic user",
        "description": "update a specefic user by its id.",
        "tags": ["Users"],
        "requestBody": {
          "description": "article data for create",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": { "type": "string", "example": "mahyar" },
                  "email": { "type": "string", "example": "m@m.com" },
                  "password": { "type": "string", "example": "123456AA" },
                  "isAdmin": { "type": "boolean", "example": true },
                  "isPremium": { "type": "boolean", "example": true }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "update a user successfully",
            "content": {
              "application/json": { "example": { "message": "user update successfully" } }
            }
          },
          "404": { "description": "user not found" }
        }
      }
    }
  },
  "components": {},
  "tags": [
    { "name": "Article", "description": "All about article endpoints" },
    {
      "name": "Authentication",
      "description": "User authentication and authorization endpoints"
    },
    { "name": "Users", "description": "All about article endpoints" }
  ]
}
